### ISSUE TITLE
process.env.HOME isn't always defined

### ISSUE THREAD

**Issue by zeke** [rvagg/pygmentize-bundled-cached#2]
This isn't a bug per se, but something I encounterd.

![screen shot 2015-01-22 at 4 20 49 pm](https://cloud.githubusercontent.com/assets/2289/5867572/bd3dad18-a252-11e4-893f-270172fc5f66.png)

**Comment by rvagg** [comment]
Ouch, is this being done from an upstart environment or something where you have to explicitly set `$HOME`?

How's this for an alternative:

* In the absence of `$HOME`, print a warning to stderr and default to cwd
* Add an option to set the `cachePath` when you make a new instance of this lib

**Comment by zeke** [comment]
upstart: yep
proposed alternative: yep
:)

**Comment by rvagg** [comment]
well, now you know that `$HOME` in an upstart config is always a good idea anyway!

I'll implement the proposed fix today

**Comment by rvagg** [comment]
see a68af80

published as 1.1.0, thanks for reporting @zeke 

btw, if this is running on npmwww, what size cache is it getting to? it must be massive!

**Comment by zeke** [comment]
Nice! Thanks for adding this. Incidentally, this patch will allow people to use `pygmentize-bundled-cached` on heroku, where only `/tmp` is writeable. Bonus!

pygmentize-bundled is built into [npm's new markdown parser thingy](https://github.com/npm/marky-markdown/blob/master/lib/render.js#L18-L24), but I have it disabled on production for now because READMEs like https://www.npmjs.com/package/async take several seconds to parse with pygments highlighting enabled. More info on that here: https://github.com/npm/marky-markdown/pull/11

We are caching stuff in redis, so we'll probably end up just using `pygmentize-bundled` instead of `pygmentize-bundled-cached` so as to avoid accidentally running out of disk space.
